# Generated by Django 6.1.1 on 2026-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_options_books_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='available_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
