# Generated by Django 6.1.1 on 2026-10-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='available_quantity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='books',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
